import { describe,expect,it } from 'vitest';
import { mkdtempSync,rmSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { compactLabel, poolListingPage, poolListingSummary, rankPoolListing, unavailablePoolListingPage, type PoolListing, type PoolListingItem } from '../apps/telegram-lp-bot/src/pool-selection-ux.js';
import { telegramCallbackData } from '../apps/telegram-lp-bot/src/callback-data.js';

function listing(){const items:PoolListingItem[]=[...Array.from({length:12},(_,i)=>({section:'v4_eligible' as const,rank:i,label:`v4 ${String(i).padStart(2,'0')}`,data:`v4-pool:${i}`,pair:`AI/USDG`,protocol:'v4' as const,feeLabel:'1.00%',tvlUsd:i===0?491.06:null,statusLabel:'✅ Ready'})),{section:'v4_checking' as const,rank:12,label:'v4 checking',data:'',pair:'AI/USDG',protocol:'v4' as const,feeLabel:'4.00%',tvlUsd:null,statusLabel:'🟡 Checking',reason:'Waiting for fresh worker evidence.'},{section:'v4_no_active' as const,rank:13,label:'v4 zero',data:'',pair:'AI/USDG',protocol:'v4' as const,feeLabel:'5.00%',tvlUsd:0,statusLabel:'⚪ No active liquidity',reason:'Fresh StateView active liquidity is zero.'},{section:'v4_unavailable' as const,rank:14,label:'v4 unsupported',data:'',pair:'AI/USDG',protocol:'v4' as const,feeLabel:'99.00%',tvlUsd:1,statusLabel:'❌ Unsupported',reason:'EXTREME_STATIC_FEE'}];return {tokenSymbol:'AI',tokenAddress:'0xai',items:rankPoolListing(items),counts:{v4Eligible:12,v3Eligible:0,v4Unavailable:1,zeroLiquidity:1,checking:1,unsupported:1}} satisfies PoolListing;}

describe('Telegram all-pool v4-first listing',()=>{
 it('keeps every v4 pool visible across first, middle, and last pages',()=>{const value=listing(),first=poolListingPage(value,0),middle=poolListingPage(value,1),last=poolListingPage(value,99);expect(first.totalPages).toBe(2);expect(first.items).toHaveLength(9);expect(middle.items).toHaveLength(6);expect(last.current).toBe(1);expect([...first.items,...middle.items]).toHaveLength(15);expect([...first.items,...middle.items].filter(x=>x.section==='v4_eligible')).toHaveLength(12);expect([...first.items,...middle.items].filter(x=>x.section!=='v4_eligible')).toHaveLength(3);});
 it('places ready v4 rows first and exposes callbacks only for executable pools',()=>{const items=listing().items;expect(items.slice(0,12).map(x=>x.data)).toEqual(Array.from({length:12},(_,i)=>`v4-pool:${i}`));expect(items.slice(12).every(x=>x.protocol==='v4'&&!x.data)).toBe(true);expect(items.every(x=>!x.data.includes('unavailable')&&!x.data.includes('checking'))).toBe(true);});
 it('has stable page boundaries',()=>{const value=listing(),first=poolListingPage(value,0),last=poolListingPage(value,1);expect(first.hasPrevious).toBe(false);expect(first.hasNext).toBe(true);expect(last.hasPrevious).toBe(true);expect(last.hasNext).toBe(false);});
 it('renders terminal-evidence summary and Telegram-safe labels without transaction data',()=>{const value=listing(),first=poolListingSummary(value,0),second=poolListingSummary(value,1);expect(first).toContain('✅ Pools · 15 found · page 1/2');expect(first).toContain('v4 prioritized');expect(first).toContain('Eligible: ⚡ v4 12 · v3 0');expect(first).toContain('Other: checking 1 · no liquidity 1 · not initialized 0 · evidence unavailable 0 · unsupported 1');expect(first).toContain('1. AI/USDG · ⚡ v4 · 1.00% fee · ✅ Ready');expect(first).toContain('TVL $491.06 · 24h vol unavailable');expect(second).toContain('✅ Pools · 15 found · page 2/2');expect(second).toContain('🟡 Checking');expect(second).toContain('❌ Unsupported');expect(compactLabel('x'.repeat(100))).toHaveLength(58);expect(value.items.every(x=>!x.data.includes('open-canary')&&!x.data.includes('v4-open'))).toBe(true);});
 it('shows unavailable and checking v4 pools in normal pages as information-only rows',()=>{const unavailable:PoolListing={tokenSymbol:'AI',tokenAddress:'0xai',items:[{section:'v4_unavailable',rank:0,label:'UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG',data:'',pair:'AI/USDG',protocol:'v4',feeLabel:'99.00%',tvlUsd:.21,statusLabel:'❌ Unsupported',reason:'EXTREME_STATIC_FEE'}],unavailableItems:[{section:'v4_unavailable',rank:0,label:'UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG',data:''}],counts:{v4Eligible:0,v3Eligible:0,v4Unavailable:1,zeroLiquidity:0,checking:0,evidenceUnavailable:0,unsupported:1}};const normal=poolListingPage(unavailable,0),informational=unavailablePoolListingPage(unavailable,0),summary=poolListingSummary(unavailable,0);expect(normal.items).toHaveLength(1);expect(normal.items[0]?.data).toBe('');expect(summary).toContain('❌ Unsupported');expect(summary).toContain('Reason: EXTREME_STATIC_FEE');expect(informational.items).toHaveLength(1);expect([...normal.items,...informational.items].every(item=>!item.data.startsWith('v4-pool:')&&!item.data.startsWith('pool:'))).toBe(true);});
 it('keeps legacy unavailable rows visible but non-executable',()=>{const legacy:PoolListing={tokenSymbol:'AI',tokenAddress:'0xai',items:[{section:'v4_unavailable',label:'UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG',data:''}],counts:{v4Eligible:0,v3Eligible:0,v4Unavailable:1,zeroLiquidity:0,checking:0,unsupported:1}};expect(poolListingPage(legacy,0).items).toHaveLength(1);expect(unavailablePoolListingPage(legacy,0).items).toHaveLength(1);expect(poolListingSummary(legacy,0)).toContain('❌ Unsupported');});
 it('renders all v4 rows in the normal listing while buttons stay executable-only',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),persist=source.slice(source.indexOf('function persistPoolListing'),source.indexOf('async function rankV4CandidatesForTelegram')),normal=source.slice(source.indexOf('function poolListingRender'),source.indexOf('function messageNotModified')),unavailable=source.slice(source.indexOf('function renderUnavailablePoolListing'),source.indexOf('async function pageUnavailablePoolListing'));expect(persist).toContain('...input.v4Candidates.map');expect(persist).toContain('tokenListingName(input.tokenSymbol');expect(persist).toContain('v3Eligible: 0');expect(normal).toContain('view.items.filter((item) => item.data)');expect(normal).toContain('direct-lookup-retry:');expect(unavailable).toContain('informational only. They cannot be selected or executed.');expect(unavailable).not.toContain('v4-pool:');expect(source).toContain('bot.callbackQuery(/^pool-unavailable-page:([^:]+):(\\d+)$/');expect(source).not.toContain('bot.callbackQuery(/^pool-unavailable:/');});
 it('keeps unavailable pagination and refresh callback data within Telegram’s 64-byte limit',()=>{for(const data of ['pool-unavailable-page:00000000-0000-0000-0000-000000000000:0','pool-page:00000000-0000-0000-0000-000000000000:0','direct-lookup-retry:0x0000000000000000000000000000000000000000'])expect(Buffer.byteLength(telegramCallbackData(data),'utf8')).toBeLessThanOrEqual(64);});
 it('renders an unleased worker stall distinctly from an actively worked timeout',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),terminal=source.slice(source.indexOf('function terminalLookupRender'),source.indexOf('function persistPoolListing'));expect(terminal).toContain('DIRECT_LOOKUP_WORKER_NOT_LEASED');expect(terminal).toContain('worker did not start this request');expect(terminal).toContain('Pool lookup timed out safely.');});
 it('is deterministic under reordered input and duplicate page callbacks are read-only',()=>{const value=listing(),again=rankPoolListing([...value.items].reverse());expect(again.map(x=>x.data)).toEqual(value.items.map(x=>x.data));expect(poolListingPage(value,1)).toEqual(poolListingPage(value,1));});
 it('keeps all immutable v4 selections through pagination and supersedes them only for a replacement session',()=>{const dir=mkdtempSync(join(tmpdir(),'funi-pages-')),path=join(dir,'ledger.sqlite');migrateSqlite(path,join(process.cwd(),'infra/migrations'));const repo=new SqliteLedgerRepository(path);try{const first='first',second='second',key={currency0:'0x0000000000000000000000000000000000000001',currency1:'0x0000000000000000000000000000000000000002',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};const ids=Array.from({length:12},(_,index)=>String(repo.createV4PoolSelection({userId:'u',chatId:'c',sessionId:first,poolId:`0x${String(index).padStart(64,'0')}`,poolKey:key,discoveryBlock:1n,liquidity:1n,eligibility:true,supersedeExisting:false,expiresAtMs:2_000}).id));expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);poolListingPage(listing(),0);poolListingPage(listing(),1);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);repo.supersedeOtherV4PoolSelections('u','c',second);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===1)).toBe(true);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
});
